language: ruby
script: bundle exec rake
sudo: false

rvm:
- "1.8"
- "1.9"
- "2.0"
- "2.1"
- "2.2"
- ruby-head
- rbx
- jruby-18mode
- jruby-19mode

matrix:
  allow_failures:
  - rvm: rbx
  - rvm: ruby-head
